api/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from api import views

app_name = 'api'

urlpatterns = [
    url(r'questions/$', views.QuestionList.as_view(), name='questions'),
    url(r'questions/(?P<pk>[0-9]+)/$', views.QuestionDetail.as_view(),
        name='question'),
    url(r'get_courses/$', views.CourseList.as_view(), name='get_courses'),
    url(r'start_quiz/(?P<course_id>[0-9]+)/(?P<quiz_id>[0-9]+)/$', views.StartQuiz.as_view(),
        name='start_quiz'),
    url(r'quizzes/$', views.QuizList.as_view(), name='quizzes'),
    url(r'quizzes/(?P<pk>[0-9]+)/$', views.QuizDetail.as_view(), name='quiz'),
    url(r'questionpapers/$', views.QuestionPaperList.as_view(),
        name='questionpapers'),
    url(r'questionpapers/(?P<pk>[0-9]+)/$',
        views.QuestionPaperDetail.as_view(), name='questionpaper'),
    url(r'answerpapers/$', views.AnswerPaperList.as_view(),
        name='answerpapers'),
    url(r'validate/(?P<answerpaper_id>[0-9]+)/(?P<question_id>[0-9]+)/$',
        views.AnswerValidator.as_view(), name='validators'),
    url(r'validate/(?P<uid>[0-9]+)/$',
        views.AnswerValidator.as_view(), name='validator'),
    url(r'course/(?P<pk>[0-9]+)/$',
        views.GetCourse.as_view(), name='get_course'),
    url(r'quit/(?P<answerpaper_id>\d+)/$', views.QuitQuiz.as_view(),
        name="quit_quiz"),
    url(r'login/$', views.login, name='login')
]

urlpatterns = format_suffix_patterns(urlpatterns)

letsprepare/urls.py
from django.conf.urls import url
from letsprepare import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^show_modules/$', views.show_all_modules, name="home"),
    url(r'^exam/$', views.show_all_quizzes, name='quizzes'),
    url(r'^results/$', views.show_results, name='results'),
    url(r'^buy/$', views.show_all_on_sale, name='buy'),
    url(r'^assign_quizzes/$', views.assign_quizzes, name='assign_quizzes'),
    url(r'^report_error/$', views.report_error, name='report_error'),
    url(r'^send_otp/$', views.send_otp, name='report_error'),
    url(r'^verify_payment/$', views.verify_payment, name='get_payment')
]

online_test/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from online_test import views
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'online_test.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('allauth.urls')),
    url(r'^reset_password/', views.reset_password, name='reset_password'),
    url(r'^terms/', views.return_terms, name='terms'),
    url(r'^$', views.index, name='index'),
    url(r'^exam/', include(('yaksh.urls', 'yaksh'))),
    url(r'^exam/reset/', include('django.contrib.auth.urls')),
    url(r'^', include('social_django.urls', namespace='social')),
    url(r'^grades/', include(('grades.urls', 'grades'))),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^letsprepare/', include(('letsprepare.urls', 'letsprepare'), namespace='letsprepare')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yaksh/urls.py
from django.conf.urls import url
from django.urls import path
from yaksh import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name="logout"),
    url(r'^contact_us/$', views.contact_us, name="contact_us"),
    url(r'^update_email/$', views.update_email, name="update_email"),
    url(r'^activate/(?P<key>.+)$', views.activate_user, name="activate"),
    url(r'^new_activation/$', views.new_activation, name='new_activation'),
    url(r'^toggle_moderator/$', views.toggle_moderator_role,
        name='toggle_moderator'),
    url(r'^quizzes/$', views.quizlist_user, name='quizlist_user'),
    url(r'^results/$', views.results_user),
    # url(r'^start/(?P<questionpaper_id>\d+)/$', views.lp_start, name="start_quiz"),
    url(r'^start/(?P<questionpaper_id>\d+)/(?P<module_id>\d+)/'
        '(?P<course_id>\d+)/$', views.start, name="start_quiz"),
    url(r'^start/(?P<attempt_num>\d+)/(?P<module_id>\d+)/'
        '(?P<questionpaper_id>\d+)/(?P<course_id>\d+)/$', views.start,
        name="start_quiz"),
    url(r'^quit/(?P<attempt_num>\d+)/(?P<module_id>\d+)/'
        '(?P<questionpaper_id>\d+)/(?P<course_id>\d+)/$', views.quit,
        name="quit_quiz"),
    url(r'^complete/$', views.complete, name="complete"),
    url(r'^complete/(?P<attempt_num>\d+)/(?P<module_id>\d+)/'
        '(?P<questionpaper_id>\d+)/(?P<course_id>\d+)/$', views.complete,
        name="complete"),
    url(r'^register/$', views.user_register, name="register"),
    url(r'^(?P<q_id>\d+)/check/$', views.check, name="check"),
    url(r'^get_result/(?P<uid>\d+)/(?P<course_id>\d+)/(?P<module_id>\d+)/$',
        views.get_result),
    url(r'^(?P<q_id>\d+)/check/(?P<attempt_num>\d+)/(?P<module_id>\d+)/'
        '(?P<questionpaper_id>\d+)/(?P<course_id>\d+)/$',
        views.check, name="check"),
    url(r'^(?P<q_id>\d+)/skip/(?P<attempt_num>\d+)/(?P<module_id>\d+)/'
        '(?P<questionpaper_id>\d+)/(?P<course_id>\d+)/$',
        views.skip, name="skip_question"),
    url(r'^(?P<q_id>\d+)/skip/(?P<next_q>\d+)/(?P<attempt_num>\d+)/'
        '(?P<module_id>\d+)/(?P<questionpaper_id>\d+)/(?P<course_id>\d+)/$',
        views.skip, name="skip_question"),
    url(r'^enroll_request/(?P<course_id>\d+)/$', views.enroll_request,
        name='enroll_request'),
    url(r'^self_enroll/(?P<course_id>\d+)/$', views.self_enroll,
        name='self_enroll'),
    url(r'^view_answerpaper/(?P<questionpaper_id>\d+)/(?P<course_id>\d+)$',
        views.view_answerpaper, name='view_answerpaper'),
    url(r'^download/user_assignment/(?P<question_id>\d+)/(?P<user_id>\d+)/'
        '(?P<quiz_id>\d+)/(?P<course_id>\d+)$',
        views.download_assignment_file, name="download_user_assignment"),
    url(r'^show_lesson/(?P<lesson_id>\d+)/(?P<module_id>\d+)/'
        '(?P<course_id>\d+)/$', views.show_lesson, name='show_lesson'),
    url(r'^quizzes/view_module/(?P<module_id>\d+)/(?P<course_id>\d+)/$',
        views.view_module, name='view_module'),
    url(r'^next_unit/(?P<course_id>\d+)/(?P<module_id>\d+)/'
        '(?P<current_unit_id>\d+)/$', views.get_next_unit, name='next_unit'),
    url(r'^next_unit/(?P<course_id>\d+)/(?P<module_id>\d+)/$',
        views.get_next_unit, name='next_unit'),
    url(r'^next_unit/(?P<course_id>\d+)/(?P<module_id>\d+)/'
        '(?P<current_unit_id>\d+)/(?P<first_unit>\d+)/$',
        views.get_next_unit, name='next_unit'),
    url(r'^course_modules/(?P<course_id>\d+)/$',
        views.course_modules, name='course_modules'),
    url(r'^forum/(?P<course_id>\d+)/$',
        views.course_forum,
        name='course_forum'),
    url(r'^forum/(?P<course_id>\d+)/post/(?P<uuid>[0-9a-f-]+)/$',
        views.post_comments,
        name='post_comments'),
    url(r'^forum/(?P<course_id>\d+)/post/(?P<uuid>[0-9a-f-]+)/delete/',
        views.hide_post,
        name='hide_post'),
    url(r'^forum/(?P<course_id>\d+)/comment/(?P<uuid>[0-9a-f-]+)/delete/',
        views.hide_comment,
        name='hide_comment'),
    url(r'^manage/$', views.prof_manage, name='manage'),
    url(r'^manage/addquestion/$', views.add_question, name="add_question"),
    url(r'^manage/addquestion/(?P<question_id>\d+)/$', views.add_question,
        name="add_question"),
    url(r'^manage/add_exercise/(?P<course_id>\d+)/(?P<module_id>\d+)/$',
        views.add_exercise, name='add_exercise'),
    url(r'^manage/add_exercise/(?P<course_id>\d+)/(?P<module_id>\d+)/(?P<quiz_id>\d+)$',
        views.add_exercise, name='edit_exercise'),
    url(r'^manage/addquiz/(?P<course_id>\d+)/(?P<module_id>\d+)/$',
        views.add_quiz, name='add_quiz'),
    url(r'^manage/addquiz/(?P<course_id>\d+)/(?P<module_id>\d+)/(?P<quiz_id>\d+)$',
        views.add_quiz, name='edit_quiz'),
    url(r'^manage/gradeuser/$', views.grade_user, name="grade_user"),
    url(r'^manage/gradeuser/(?P<quiz_id>\d+)/(?P<course_id>\d+)/$',
        views.grade_user, name="grade_user"),
    url(r'^manage/gradeuser/(?P<quiz_id>\d+)/(?P<user_id>\d+)/'
        '(?P<course_id>\d+)/$',
        views.grade_user, name="grade_user"),
    url(r'^manage/gradeuser/(?P<quiz_id>\d+)/(?P<user_id>\d+)/'
        '(?P<attempt_number>\d+)/(?P<course_id>\d+)/$',
        views.grade_user, name="grade_user"),
    url(r'^manage/questions/$', views.show_all_questions,
        name="show_questions"),
    url(r'^manage/monitor/$', views.monitor, name="monitor"),
    url(r'^manage/monitor/(?P<quiz_id>\d+)/(?P<course_id>\d+)/$',
        views.monitor, name="monitor"),
    url(r'^manage/user_data/(?P<user_id>\d+)/(?P<questionpaper_id>\d+)/'
        '(?P<course_id>\d+)/$',
        views.user_data, name="user_data"),
    url(r'^manage/user_data/(?P<user_id>\d+)/$', views.user_data),
    url(r'^manage/designquestionpaper/(?P<course_id>\d+)/(?P<quiz_id>\d+)/'
        '(?P<questionpaper_id>\d+)/$',
        views.design_questionpaper, name='designquestionpaper'),
    url(r'^manage/designquestionpaper/(?P<course_id>\d+)/(?P<quiz_id>\d+)/$',
        views.design_questionpaper, name='designquestionpaper'),
    url(r'^manage/statistics/question/(?P<questionpaper_id>\d+)/'
        '(?P<course_id>\d+)/$',
        views.show_statistics, name="show_statistics"),
    url(r'^manage/statistics/question/(?P<questionpaper_id>\d+)/'
        '(?P<attempt_number>\d+)/(?P<course_id>\d+)/$',
        views.show_statistics, name="show_statistics"),
    url(r'^manage/download_quiz_csv/(?P<course_id>\d+)/(?P<quiz_id>\d+)/$',
        views.download_quiz_csv, name="download_quiz_csv"),
    url(r'^manage/duplicate_course/(?P<course_id>\d+)/$',
        views.duplicate_course, name='duplicate_course'),
    url(r'manage/courses/$', views.courses, name='courses'),
    url(r'manage/add_course/$', views.add_course, name='add_course'),
    url(r'manage/edit_course/(?P<course_id>\d+)$', views.add_course,
        name='edit_course'),
    url(r'manage/course_detail/(?P<course_id>\d+)/$', views.course_detail,
        name='course_detail'),

    url(r'manage/enroll/(?P<course_id>\d+)/$', views.enroll_reject_user,
        name="enroll_reject_user"),
    url(r'manage/enroll/(?P<course_id>\d+)/(?P<user_id>\d+)/$',
        views.enroll_user, name="enroll_user"),
    url(r'manage/reject/(?P<course_id>\d+)/(?P<user_id>\d+)/$',
        views.reject_user, name="reject_user"),
    url(r'manage/enrolled/reject/(?P<course_id>\d+)/(?P<user_id>\d+)/$',
        views.reject_user, {'was_enrolled': True},
        name="reject_enrolled_user"),
    url(r'manage/enrolled/reject/(?P<course_id>\d+)/$',
        views.enroll_reject_user, {'was_enrolled': True},
        name="reject_enrolled_users"),
    url(r'manage/enroll/rejected/(?P<course_id>\d+)/(?P<user_id>\d+)/$',
        views.enroll_user, {'was_rejected': True},
        name="enroll_rejected_user"),
    url(r'manage/enroll/rejected/(?P<course_id>\d+)/$',
        views.enroll_reject_user, {'was_rejected': True},
        name="enroll_rejected_users"),

    url(r'manage/upload_users/(?P<course_id>\d+)/$', views.upload_users,
        name="upload_users"),
    url(r'manage/send_mail/(?P<course_id>\d+)/$', views.send_mail,
        name="send_mail"),

    url(r'manage/toggle_status/(?P<course_id>\d+)/$',
        views.toggle_course_status, name="toggle_course_status"),
    url(r'^questions/filter$', views.questions_filter,
        name="questions_filter"),
    url(r'^editprofile/$', views.edit_profile, name='edit_profile'),
    url(r'^viewprofile/$', views.view_profile, name='view_profile'),

    url(r'^manage/searchteacher/(?P<course_id>\d+)/$', views.search_teacher,
        name="search_teacher"),
    url(r'^manage/addteacher/(?P<course_id>\d+)/$', views.add_teacher,
        name='add_teacher'),
    url(r'^manage/remove_teachers/(?P<course_id>\d+)/$', views.remove_teachers,
        name='remove_teacher'),
    url(r'^manage/download_questions/$', views.show_all_questions,
        name="download_questions"),
    url(r'^manage/upload_questions/$', views.show_all_questions,
        name="upload_questions"),
    url(r'^manage/create_modules/$', views.create_modules,
        name="create_modules"),
    url(r'^manage/regrade/paper/question/(?P<course_id>\d+)/'
        '(?P<questionpaper_id>\d+)/(?P<question_id>\d+)/$',
        views.regrade, name='regrade_by_quiz'),
    url(r'^manage/regrade/user/(?P<course_id>\d+)/(?P<questionpaper_id>\d+)/'
        '(?P<answerpaper_id>\d+)/$', views.regrade, name='regrade_by_user'),
    url(r'^manage/regrade/user/question/(?P<course_id>\d+)/'
        '(?P<questionpaper_id>\d+)/(?P<answerpaper_id>\d+)/'
        '(?P<question_id>\d+)/', views.regrade, name='regrade_by_question'),
    url(r'^manage/(?P<mode>godmode|usermode)/(?P<quiz_id>\d+)/'
        '(?P<course_id>\d+)/$', views.test_quiz, name="test_quiz"),
    url(r'^manage/create_demo_course/$', views.create_demo_course,
        name="create_demo_course"),
    url(r'^manage/courses/download_course_csv/(?P<course_id>\d+)/$',

yaksh/templates/base.html
{% load static %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>
    {% block title %}
    {% endblock %}
    </title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="apple-touch-icon" href="apple-touch-icon.png">

  <link rel="stylesheet" href="{% static 'yaksh/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'yaksh/css/custom.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'yaksh/css/animate.min.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'yaksh/css/font-awesome.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'yaksh/css/ontop.css' %}" type="text/css" />


  {% block meta %}
  <meta charset="utf-8">
  <meta name="description" content="">
  <meta name="author" content="">
  {% endblock %}

  {% block css %}
  {% endblock %}

 

  <script language="JavaScript" type="text/javascript" src="{% static 'yaksh/js/popper.min.js' %}"></script>
  <script language="JavaScript" type="text/javascript" src="{% static 'yaksh/js/jquery-3.3.1.min.js' %}"></script>
  <script language="JavaScript" type="text/javascript" src="{% static 'yaksh/js/bootstrap.min.js' %}"></script>
  <script language="JavaScript" type="text/javascript" src="{% static 'yaksh/js/wow.min.js' %}"></script>
 
  <script>
      new WOW().init();
  </script>
  {% block script %}
  {% endblock %}
  <style>
  * {
    -webkit-user-select: none; /* Chrome all / Safari all */
    -moz-user-select: none;    /* Firefox all             */
    -ms-user-select: none;     /* Internet Explorer  10+  */
     user-select: none;        /* Likely future           */
  }
</style>
</head>

<body {% block onload %} {% endblock %} class="yaksh">

  <div id="ontop">
    <div id="state">
      Checking...<img src="{% static 'yaksh/images/check_answer.gif' %}"/>
    </div></div>

    
  
  {% block nav %}
  {% endblock %}

     <div class="base-content">
         <div class="header">
             <h3><center>{% block pagetitle %}{% endblock pagetitle %}</center></h3>
         </div>
         <h4><center>{% block subtitle %}{% endblock %}</center></h4>
         {% block content %}
         {% endblock %}
     </div>
     

  {% block footer %}
  {% endblock %}

</body>
</html>

yaksh/templates/base2.html
{% load static %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>
    {% block title %}
    {% endblock %}
    </title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="apple-touch-icon" href="apple-touch-icon.png">

  <link rel="stylesheet" href="{% static 'yaksh/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'yaksh/css/custom.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'yaksh/css/animate.min.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'yaksh/css/font-awesome.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'yaksh/css/ontop.css' %}" type="text/css" />


  {% block meta %}
  <meta charset="utf-8">
  <meta name="description" content="">
  <meta name="author" content="">
  {% endblock %}

  {% block css %}
  {% endblock %}

 

  <script language="JavaScript" type="text/javascript" src="{% static 'yaksh/js/popper.min.js' %}"></script>
  <script language="JavaScript" type="text/javascript" src="{% static 'yaksh/js/jquery-3.3.1.min.js' %}"></script>
  <script language="JavaScript" type="text/javascript" src="{% static 'yaksh/js/bootstrap.min.js' %}"></script>
  <script language="JavaScript" type="text/javascript" src="{% static 'yaksh/js/wow.min.js' %}"></script>
 
  <script>
      new WOW().init();
  </script>
  {% block script %}
  {% endblock %}
</head>

<body {% block onload %} {% endblock %} class="yaksh">

  <div id="ontop">
    <div id="state">
      Checking...<img src="{% static 'yaksh/images/check_answer.gif' %}"/>
    </div></div>

    
  
  {% block nav %}
  {% endblock %}

         {% block content %}
         {% endblock %}
     

  {% block footer %}
  {% endblock %}

</body>
</html>

yaksh/templates/manage.html
{% extends "base.html" %}
{% load static %}

{% block nav %}
<nav class="navbar navbar-expand-sm navbar-dark bg-primary fixed-top">
    <a class="navbar-brand" href="{% url 'yaksh:index' %}">
    <img src="{% static 'yaksh/images/lp.png' %}" alt="LETSPREPARE">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'yaksh:show_questions' %}">
            Questions
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'yaksh:courses' %}">
            Courses
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'yaksh:grade_user' %}">
            Quizzes
          </a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'yaksh:view_notifications' %}">
            <i class="fa fa-bell" style="size: 18px"></i>&nbsp;Notifications
            {% if request.custom_notifications > 0 %}
                <span class="badge badge-success badge-pill">
                    {{request.custom_notifications}}
                </span>
            {% endif %}
          </a>
        </li>
        <li class="nav-item dropdown my-lg-0" style="font-size: 1.2rem">
            <a class="dropdown-toggle nav-link" id="user_dropdown" data-toggle="dropdown" href="#">{{user.get_full_name|title}}
            </a>
            <div class="dropdown-menu dropdown-menu-right">
            <a class="dropdown-item" href="{% url 'yaksh:edit_profile' %}">
                <i class="fa fa-user"></i>  My Profile
            </a>
            <div class="dropdown-divider"></div>
            {% if user.profile.is_moderator %}
                <a class="dropdown-item" href="{% url 'yaksh:toggle_moderator' %}"><i class="fa fa-exchange"></i>
                    Switch To Student
                </a>
                <div class="dropdown-divider"></div>
            {% endif %}
            <a class="dropdown-item" href="{% url 'password_change' %}">
                <i class="fa fa-key"></i> Change Password
            </a>
            <div class="dropdown-divider"></div>
                <a class="dropdown-item" id="user_logout" href="{% url 'yaksh:logout' %}">
                    <i class="fa fa-sign-out"></i> Logout
                </a>
            </div>
        </li>
    </ul>
    </div>
</nav>

<!-- iframe div for video embed -->
<div id="iframe_div" style="display: none;">
  <iframe class="embed-responsive-item" id="video_frame" width="640" height="480" allowfullscreen>
  </iframe>
</div>
<!-- end iframe div -->

<!-- Dialog to video embed -->
<div id="dialog_iframe" title="Embed Video URL" style="display: none;">
  <div class="input-group mb-3">
    <input id="url" name="url" type="text" required="true" class="form-control" placeholder="Enter video link">
    <div class="input-group-append">
        <input type="button" id="submit_info" name="submit_info" class="btn btn-primary" value="Submit" />
    </div>
  </div>
  <div id="error_div" style="display: none;">
      <b> Please enter URL</b>
  </div>
  <div id="copy_div">
      <br>
      <label>Paste HTML to embed in website:</label>
      <textarea id="html_text" class="form-control" rows="5" cols="100"></textarea>
      <br>
      <a class="btn btn-secondary" id="copy" data-toggle="tooltip" title="Copy to Clipboard">
          <i class="fa fa-clipboard" aria-hidden="true"></i>
      </a>
  </div>
</div>
<!-- end dialog -->

{% endblock %}
{% block content %}
<div class="container">
    {% block main %}
    {% endblock %}
</div>
{% endblock %}

{% block footer %}
{% endblock %}

yaksh/templates/user.html
{% extends "base.html" %}
{% load static %}
{% block nav %}
<div class="container-fluid">
    <nav class="navbar navbar-expand-sm navbar-dark bg-primary fixed-top">
        <a class="navbar-brand" href="{% url 'yaksh:index' %}">
        <img src="{% static 'yaksh/images/lp.png' %}" alt="YAKSH">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a class="nav-link" href="{% url 'yaksh:index' %}"><i class="fa fa-university" style="size: 18px"></i>&nbsp;Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'letsprepare:results' %}"><i class="fa fa-bar-chart" style="size: 18px"></i>&nbsp;Results</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'letsprepare:buy' %}"><i class="fa fa-unlock" style="size: 18px"></i>&nbsp;Unlock Tests</a></li>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item dropdown my-lg-0" style="font-size: 1.2rem">
                <a class="dropdown-toggle nav-link" id="user_dropdown" data-toggle="dropdown" href="#">{{user.get_full_name|title}}
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item" href="{% url 'yaksh:edit_profile' %}">
                    <i class="fa fa-user"></i>  My Profile
                </a>
                <div class="dropdown-divider"></div>
                {% if user.profile.is_moderator %}
                    <a class="dropdown-item" href="{% url 'yaksh:toggle_moderator' %}"><i class="fa fa-exchange"></i>
                        Switch To Moderator
                    </a>
                    <div class="dropdown-divider"></div>
                {% endif %}
                <a class="dropdown-item" href="{% url 'password_change' %}">
                    <i class="fa fa-key"></i> Change Password
                </a>
                <div class="dropdown-divider"></div>
                    <a class="dropdown-item" id="user_logout" href="{% url 'yaksh:logout' %}">
                        <i class="fa fa-sign-out"></i> Logout
                    </a>
                </div>
            </li>
            {% endif %}
        </ul>
        </div>
    </nav>
</div>
{% endblock %}


{% block content %}  
  {% block main %}
    {% block navtab %}
    {% endblock %}
  {% endblock %}
{% endblock %}